SOUND_BUSINESS_BUY = "buttons/button14.wav"
SOUND_BUSINESS_PREVENT_BUY = "buttons/button11.wav"
SOUND_BUSINESS_PREVENT_RESPONSE = "buttons/button3.wav"
SOUND_BUSINESS_PREVENT_TIMEOUT = "buttons/button11.wav"
SOUND_CUSTOM_CHAT_SOUND = ""
SOUND_F1_MENU_UNANCHOR = "buttons/lightswitch2.wav"
SOUND_MENU_BUTTON_ROLLOVER = "ui/buttonrollover.wav"
SOUND_MENU_BUTTON_PRESSED = "ui/buttonclickrelease.wav"
SOUND_NOTIFY = {"garrysmod/content_downloaded.wav", 50, 250}
SOUND_CHAR_HOVER = {"buttons/button15.wav", 35, 250}
SOUND_CHAR_CLICK = {"buttons/button14.wav", 35, 255}
SOUND_CHAR_WARNING = {"friends/friend_join.wav", 40, 255}
SOUND_BAG_RESPONSE = {"physics/cardboard/cardboard_box_impact_soft2.wav", 50}
SOUND_ATTRIBUTE_BUTTON = {"buttons/button16.wav", 30, 255}
SOUND_VENDOR_CLICK = {"buttons/button15.wav", 30, 250}